### ISSUE TITLE
How to specify the amount of servers in parallell

### ISSUE THREAD

**Issue by andreas-ullrich** [rexyai/RestRserve#178]
Hi

thank you so much for this package!
I have the following question:
Every time i start RestRserve i get the following printout:

-- running Rserve in this R session (pid=20580), 2 server(s) --

Is it possible to run more than 2 servers? 
Where can i specify the amount?
Or does Rserve scale up automatically?

BR

**Comment by artemklevtsov** [comment]
Rserve forks main process when handle requests,
From the [docs](https://www.r-project.org/conferences/DSC-2003/Proceedings/Urbanek.pdf):
> Rserveuses fork to create a new, initialized process as soon as a new incoming connection arrives. For most
current operating systems fork has little overhead, since the same memory is used for the code and data segment is copied on write only. This allows very fast spawning of Rprocesses for the clients. At the same time this method guarantees that each connection receives a clean, separate data space, unpolluted by previous connections which is independent of all ther Rinstances.
So you can't define which cores will be used.
